# """
# Django settings for LinkedinxDCard project.
#
# Generated by 'django-admin startproject' using Django 1.11.6.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/1.11/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/1.11/ref/settings/
# """
#
# import os
# from celery.schedules import crontab
#
# # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'ie_i18tw@u%s-2)^7(9%)qa+@iv8c%r6(e3ki0q2lj45!e&m2&'
#
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
#
# # '54.254.208.10' -> Singapore
# # '52.91.88.137' -> US east
# ALLOWED_HOSTS = ['54.254.208.10', '52.91.88.137' ,'localhost']
#
#
# # Application definition
#
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'rest_framework_mongoengine',
#     'user',
#     'channels',
# ]
#
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
#
# ROOT_URLCONF = 'Server.urls'
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'Server.wsgi.application'
#
#
# # Database
# # https://docs.djangoproject.com/en/1.11/ref/settings/#databases
#
# DATABASES = {
#     # 'default': {
#     #     'ENGINE': 'django.db.backends.sqlite3',
#     #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     # }
# }
#
#
# # Password validation
# # https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#
#
# # Internationalization
# # https://docs.djangoproject.com/en/1.11/topics/i18n/
#
# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'Asia/Taipei'
#
# USE_I18N = True
#
# USE_L10N = True
#
# USE_TZ = True
#
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/1.11/howto/static-files/
#
# STATIC_URL = '/static/'
#
# # STATICFILES_DIRS = [(os.path.join(BASE_DIR, '/static'))]
#
#
#
# # mongoemgine Setting
# MONGODB_HOST = 'mongodb://Harrison:dots2017@ds059207.mlab.com:59207/dots'
# MONGODB_DB_NAME = 'dots'
# MONGODB_USER = 'Harrison'
# MONGODB_PASSWORD = 'dots2017'
#
#
# # Channels Setting
# ASGI_APPLICATION = "Server.routing.application"
#
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("localhost", 6379)],
#         },
#     },
# }
#
#
# # Celery Setting
#
# # broker: rabbitmq
# # rabbitmq setting: http://docs.celeryproject.org/en/latest/getting-started/brokers/rabbitmq.html#setting-up-rabbitmq
# CELERY_BROKER_URL = 'amqp://junctionRD:junctionRD@localhost:5672/junctionDev'
# CELERY_RESULT_BACKEND = 'amqp://junctionRD:junctionRD@localhost:5672/junctionDev'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_ENABLE_UTC = True
# CELERY_TIMEZONE = 'Asia/Taipei'
# CELERY_BEAT_SCHEDULE = {
#     'draw_card': {
#         'task': 'user.tasks.draw_card_with_algorithm',
#         'schedule': crontab(minute=0, hour=4)
#         # 'schedule': crontab()
#     },
#     'update_card': {
#         'task': 'user.tasks.update_card',
#         'schedule': crontab(minute=0, hour=16)
#         # 'schedule': crontab(minute='*/2')
#     }
# }
#
# # Boto3 Setting
# AWS_ACCESS_KEY_ID = 'AKIAIFXMDZGFXF2IVTUQ'
# AWS_SECRET_ACCESS_KEY = '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'
# AWS_BUCKET_NAME = 'junction-server'
# AWS_S3_REGION =  'ap-southeast-1'
#
# # Email Setting
# EMAIL_BACKEND = 'django_ses.SESBackend'
# AWS_ACCESS_KEY_ID = 'AKIAIFXMDZGFXF2IVTUQ'
# AWS_SECRET_ACCESS_KEY = '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'
# AWS_SES_REGION_NAME = 'us-east-1'
# AWS_SES_REGION_ENDPOINT = 'email.us-east-1.amazonaws.com'
# AWS_SES_CONFIGURATION_SET = 'JunctionMail'
# MAIL_FILE = os.path.join(BASE_DIR, 'source/testMail.txt')
#
# # APNS Setting
# APNS_CERT = os.path.join(BASE_DIR, 'source/PushNotification_Production.pem')
# APNS_TOPIC = 'com.junctioninsights.junction'
# USE_SANDBOX = False